sudo: required

services:
  - docker

before_script:
  - >
      docker build -t idp . &&
      docker run --rm -p 8080:8080 --name idp -t idp

script:
  - >
      IDP_VERSION=$(sed -rn 's/.*idp_version=([0-9]\.[0-9]\.[0-9]).*/\1/p' Dockerfile) &&
      docker exec -ti idp curl localhost:8080/idp/status

deploy:
  provider: script
  script: bash push-script.sh
  on:
    branch: master
