sudo: required

services:
  - docker

before_script:
  - >
      docker build -t idp . &&
      docker run --rm -p 8080:8080 --name idp -d -t idp

script:
  - >
      sleep 30 &&
      docker exec -ti idp curl localhost:8080/idp/status

after_script: 
  - docker stop idp

deploy:
  provider: script
  script: bash push-script.sh
  on:
    branch: master
