sudo: required

services:
  - docker

before_script:
  - docker-compose up -d --build idp

script:
  - docker exec -ti idp ip addr show 

after_script:
  - docker-compose down

deploy:
  provider: script
  script: bash push-script.sh
  on:
    branch: master
