sudo: required

services:
  - docker

before_script:
  - >
      IDP_VERSION=$(sed -rn 's/.*idp_version=([0-9]\.[0-9]\.[0-9]).*/\1/p' Dockerfile) &&
      docker build -t ${DOCKER_USERNAME}/shibboleth-idp:${IDP_VERSION}-test .

script:
  - docker exec -ti idp curl localhost:8080/idp/status

deploy:
  provider: script
  script: bash push-script.sh
  on:
    branch: master
