version: "3.6"

services:

  idp:
    build:
      context: './'
      args:
       IDP_VERSION: ${IDP_VERSION:=4.1.3}
    networks:
      - backend
      - frontend
    ports:
      - "443:443"
    depends_on:
      - ldap
      - mariadb
    container_name: "${IDP_NAME}"
#     volumes:
#      - ./data/ssl:/tmp/ssl:ro

  ldap:
    image: bersace/openldap
    restart: unless-stopped
    environment:
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    networks:
      - backend
    ports:
      - "389:389"
      - "636:636"
    container_name: "${LDAP_NAME}"
    volumes:
        #- ./opt/openldap/schac-schema-1.5.ldif:/docker-entrypoint-init.d/00-schac-schema-1.5.ldif
        #- ./opt/openldap/funetEduPerson21.ldif:/docker-entrypoint-init.d/01-funetEduPerson21.ldif
      - ./opt/openldap/teppo.ldif:/docker-entrypoint-init.d/99-teppo.ldif

  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./opt/mariadb/idp-schema.sql:/docker-entrypoint-initdb.d/idp-schema.sql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "${MARIADB_NAME}"

networks:
  backend:
    internal: yes
  frontend:
